(deftheme dark-plain
  "Created 2014-11-05.")

(custom-theme-set-variables
 'dark-plain
 )

(custom-theme-set-faces
 'dark-plain
 '(default ((t (:inherit nil :stipple nil :background "black" :foreground "gray93" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal))))
 '(ahs-definition-face ((t (:underline "Orange1"))))
 '(ahs-face ((t (:underline "green1"))))
 '(ahs-plugin-defalt-face ((t (:underline t))))
 '(ahs-plugin-whole-buffer-face ((t (:background "black" :foreground "Orange1" :underline t))))
 '(buffer-menu-buffer ((t nil)))
 '(diff-added ((t (:foreground "ForestGreen"))))
 '(diff-added-face ((t (:foreground "spring green"))))
 '(diff-file-header ((t (:foreground "LightSlateBlue" :weight bold))))
 '(diff-removed ((t (:inherit diff-changed :foreground "indian red"))))
 '(ediff-current-diff-B ((((class color) (min-colors 16)) (:background "Yellow" :foreground "DarkOrchid"))))
 '(ediff-even-diff-face-B ((((class color)) (:foreground "black" :background "Grey"))))
 '(ediff-odd-diff-face-A ((((class color)) (:foreground "blue" :background "dark gray"))))
 '(font-lock-constant-face ((((class color) (min-colors 88) (background dark)) nil)))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-type-face ((t (:inherit font-lock-function-name-face))))
 '(font-lock-variable-name-face ((((class color) (min-colors 88) (background dark)) nil)))
 '(highlight ((t (:foreground "black" :background "darkseagreen2"))))
 '(info-node ((t (:foreground "white" :weight bold))))
 '(info-xref ((t (:foreground "cyan"))))
 '(match ((((class color) (min-colors 88) (background dark)) (:foreground "LightBlue1"))))
 '(mode-line ((t (:background "white" :foreground "gray30" :inverse-video t))))
 '(mode-line-buffer-id ((t (:inherit mode-line))))
 '(mode-line-inactive ((t (:inherit mode-line :background "grey75"))))
 '(magit-item-highlight ((t nil)))
 '(mumamo-background-chunk-major ((t nil)))
 '(mumamo-background-chunk-submode ((t nil)))
 '(nxml-attribute-value-face ((t nil)))
 '(nxml-char-ref-delimiter-face ((t nil)))
 '(nxml-comment-content-face ((t (:foreground "DeepSkyBlue1"))))
 '(nxml-comment-delimiter-face ((t (:foreground "DeepSkyBlue1"))))
 '(nxml-delimited-data-face ((((class color) (background dark)) nil)))
 '(nxml-delimiter-face ((((class color) (background dark)) (:inherit nxml-name-))))
 '(nxml-name-face ((((class color) (background dark)) (:foreground "steel blue"))))
 '(org-level-2-face ((((class color) (background dark)) (:foreground "LightSkyBlue1"))))
 '(org-level-3-face ((((class color) (background dark)) nil)))
 '(region ((t (:foreground "white" :background "SlateBlue4"))))
 '(secondary-selection ((t (:foreground "black" :background "paleturquoise"))))
 '(show-paren-match ((((class color) (background dark)) (:background "black" :foreground "dark turquoise"))))
 '(show-paren-mismatch ((((class color)) (:background "red" :foreground "white"))))
 '(speedbar-button-face ((((class color) (background dark)) (:background "black" :foreground "green3"))))
 '(speedbar-directory-face ((((class color) (background dark)) (:background "black" :foreground "light blue"))))
 '(speedbar-file-face ((((class color) (background dark)) (:background "black" :foreground "cyan"))))
 '(speedbar-tag-face ((((class color) (background dark)) (:background "black" :foreground "yellow"))))
 '(swbuff-default-face ((t (:background "black" :foreground "white"))))
 '(variable-pitch ((t (:family "Calibri"))))
 '(font-lock-string-face ((t (:foreground "chartreuse1"))))
 '(font-lock-keyword-face ((t (:foreground "SteelBlue2"))))
 '(js2-function-call ((t (:foreground "LightGoldenrod3"))))
 '(font-lock-function-name-face ((t (:foreground "LightGoldenrod2"))))
 '(js2-function-param ((t (:foreground "medium purple"))))
 '(font-lock-comment-face ((t (:foreground "DodgerBlue1"))))
 '(font-lock-builtin-face ((t (:foreground "light slate blue")))))

(provide-theme 'dark-plain)
